# Generated by Django 5.2.6 on 2025-09-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "return_type",
                    models.CharField(
                        choices=[
                            ("structured", "Structured"),
                            ("unstructured", "Unstructured"),
                        ],
                        max_length=20,
                    ),
                ),
                ("schema_definition", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "agents_agent",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "agents_agent_tool",
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[("system", "System"), ("user", "User")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                ("placeholders", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "agents_prompt",
                "ordering": ["prompt_type"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("tool_type", models.CharField(max_length=100)),
                ("configuration", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "agents_tool",
                "ordering": ["name"],
            },
        ),
    ]
