# Generated by Django 5.2.6 on 2025-09-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
