# Generated by Django 5.2.7 on 2025-10-07 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_alter_agent_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name (e.g., 'Crawl4AI Production')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this server provides"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="MCP endpoint URL (e.g., https://crawl4ai.../mcp/sse)"
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("sse", "Server-Sent Events"),
                            ("stdio", "Standard I/O"),
                            ("http", "Streamable HTTP"),
                        ],
                        default="sse",
                        max_length=20,
                    ),
                ),
                (
                    "tool_prefix",
                    models.CharField(
                        blank=True,
                        help_text="Prefix for tool names (e.g., 'c4ai')",
                        max_length=50,
                    ),
                ),
                ("is_healthy", models.BooleanField(default=True)),
                ("last_schema_sync", models.DateTimeField(blank=True, null=True)),
                ("auth_config", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents_mcp_server",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentMCPServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("custom_tool_prefix", models.CharField(blank=True, max_length=50)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_servers",
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mcp_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="agents.mcpserver",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_mcp_server",
                "unique_together": {("agent", "mcp_server")},
            },
        ),
        migrations.CreateModel(
            name="MCPToolDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Tool name from MCP server (e.g., 'md')",
                        max_length=200,
                    ),
                ),
                (
                    "prefixed_name",
                    models.CharField(
                        help_text="With prefix (e.g., 'c4ai_md')", max_length=200
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "input_schema",
                    models.JSONField(
                        default=dict, help_text="Tool input schema (from MCP)"
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("annotations", models.JSONField(blank=True, default=dict, null=True)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "capabilities_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Auto-extracted capabilities",
                    ),
                ),
                (
                    "required_inputs",
                    models.JSONField(
                        blank=True, default=list, help_text="Required input fields"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tools",
                        to="agents.mcpserver",
                    ),
                ),
            ],
            options={
                "db_table": "agents_mcp_tool_definition",
                "ordering": ["server", "name"],
                "unique_together": {("server", "name")},
            },
        ),
    ]
