# Generated by Django 5.2.7 on 2025-10-08 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_mcpserver_agentmcpserver_mcptooldefinition"),
        (
            "credentials",
            "0002_alter_credentialtype_options_credentialcategory_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for UI", max_length=200, unique=True
                    ),
                ),
                ("description", models.TextField(help_text="What this tool does")),
                (
                    "tool_type",
                    models.CharField(
                        help_text="Registry key (e.g., 'serp_api')", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="general", help_text="Tool category", max_length=100
                    ),
                ),
                ("requires_credential", models.BooleanField(default=False)),
                (
                    "input_schema",
                    models.JSONField(
                        default=dict, help_text="JSON schema for tool inputs"
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(
                        default=dict, help_text="JSON schema for tool outputs"
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tool-specific configuration",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether tool is available for use"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_credential_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of credential required (e.g., SERP API)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internal_tools",
                        to="credentials.credentialtype",
                    ),
                ),
            ],
            options={
                "db_table": "agents_internal_tool",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="AgentInternalTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("configuration_override", models.JSONField(blank=True, default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_tools",
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        help_text="Credential to use with this tool",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_assignments",
                        to="credentials.credential",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_assignments",
                        to="agents.internaltool",
                    ),
                ),
            ],
            options={
                "db_table": "agents_agent_internal_tool",
                "unique_together": {("agent", "tool")},
            },
        ),
    ]
