# Generated by Django 5.2.7 on 2025-10-10 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_internaltool_agentinternaltool"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID for this test session",
                        unique=True,
                    ),
                ),
                (
                    "message_history_blob",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Serialized PydanticAI ModelMessage history for conversation persistence",
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last message timestamp for cleanup/expiry",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agent being tested",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_sessions",
                        to="agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents_test_session",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="agents_test_session_7bdc30_idx"
                    ),
                    models.Index(
                        fields=["agent", "-last_activity"],
                        name="agents_test_agent_i_5b6e8f_idx",
                    ),
                ],
            },
        ),
    ]
