# Generated by Django 5.2.6 on 2025-09-26 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="status",
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_log", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("schedule", "Scheduled"),
                            ("api", "API"),
                            ("webhook", "Webhook"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflows_workflow_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("watermark_start_date", models.DateTimeField(blank=True, null=True)),
                ("watermark_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        help_text="Cron expression for scheduling",
                        max_length=100,
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=3600, help_text="Timeout in seconds"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=3, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True, help_text="Email for notifications", max_length=254
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflows_workflow_properties",
                "ordering": ["workflow__name"],
            },
        ),
    ]
