# Generated by Django 5.2.6 on 2025-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0002_remove_workflow_status_workflowexecution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflownode",
            name="visual_position",
            field=models.JSONField(
                blank=True, default=dict, help_text="Canvas position as {x, y}"
            ),
        ),
    ]
