# Generated by Django 5.2.6 on 2025-10-01 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0003_workflownode_visual_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Category identifier (e.g., data_source)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this category represents",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier for UI", max_length=50
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Node Categories",
                "db_table": "workflows_node_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NodeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "type_name",
                    models.CharField(
                        help_text="Type identifier (e.g., database, agent)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "type_description",
                    models.TextField(
                        blank=True, help_text="Description of what this node type does"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier for UI", max_length=50
                    ),
                ),
                (
                    "handler_class_name",
                    models.CharField(
                        help_text="Python class name of the node handler (e.g., DatabaseNode, AgentNode)",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this node type belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_types",
                        to="workflows.nodecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workflows_node_type",
                "ordering": ["category", "type_name"],
            },
        ),
    ]
