# Generated by Django 5.2.7 on 2025-10-02 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
        ("workflows", "0004_nodecategory_nodetype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowBuilderSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID from FastAPI workflow builder session",
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Session expiration time (typically 24 hours)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether session is still valid"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project context for this workflow session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_builder_sessions",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "workflows_builder_session",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "is_active"],
                        name="workflows_b_session_2179cf_idx",
                    ),
                    models.Index(
                        fields=["created_by", "project"],
                        name="workflows_b_created_e4634b_idx",
                    ),
                ],
            },
        ),
    ]
