# Generated by Django 5.2.7 on 2025-10-04 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0005_workflowbuildersession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowexecution",
            name="current_node_id",
            field=models.IntegerField(
                blank=True, help_text="Currently executing node", null=True
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="execution_type",
            field=models.CharField(
                choices=[
                    ("single_node", "Single Node"),
                    ("full_workflow", "Full Workflow"),
                ],
                default="single_node",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="progress_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="progress_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="target_node_id",
            field=models.IntegerField(
                blank=True, help_text="For single node execution", null=True
            ),
        ),
        migrations.AlterField(
            model_name="workflowexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("paused", "Paused"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NodeExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("node_id", models.IntegerField(help_text="WorkflowNode ID")),
                ("node_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("results", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("execution_time_seconds", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_executions",
                        to="workflows.workflowexecution",
                    ),
                ),
            ],
            options={
                "db_table": "workflows_node_execution",
                "ordering": ["workflow_execution", "started_at"],
            },
        ),
    ]
