# Generated by Django 5.2.7 on 2025-10-09 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0006_workflowexecution_current_node_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowexecution",
            name="triggered_by",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("schedule", "Scheduled"),
                    ("api", "API"),
                    ("webhook", "Webhook"),
                    ("chat", "Chat"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Unique chat session identifier",
                        unique=True,
                    ),
                ),
                (
                    "user_message",
                    models.TextField(
                        help_text="User's chat message that triggered the workflow"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of chat conversation processing",
                        max_length=20,
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured response data from workflow execution",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Workflow this chat conversation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to="workflows.workflow",
                    ),
                ),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked workflow execution (if created)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_conversations",
                        to="workflows.workflowexecution",
                    ),
                ),
            ],
            options={
                "db_table": "workflows_chat_conversation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "status"],
                        name="workflows_c_workflo_fa3307_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="workflows_c_session_5bc247_idx"
                    ),
                ],
            },
        ),
    ]
