# Generated by Django 5.2.7 on 2025-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0007_alter_workflowexecution_triggered_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowchatconversation",
            name="session_id",
            field=models.UUIDField(
                db_index=True,
                help_text="Chat session identifier (groups messages in same conversation)",
            ),
        ),
    ]
