# Generated by Django 5.2.7 on 2025-10-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0008_alter_workflowchatconversation_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowchatconversation",
            name="message_history_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Serialized PydanticAI ModelMessage history for conversation persistence",
            ),
        ),
    ]
