# Generated by Django 5.2.7 on 2025-10-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0009_workflowchatconversation_message_history_blob"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowbuildersession",
            name="pending_tasks_json",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Task queue for incremental workflow building (multi-step operations)",
            ),
        ),
    ]
