# Generated by Django 5.2.6 on 2025-09-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credentials", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="credentialtype",
            options={"ordering": ["category__name", "type_name"]},
        ),
        migrations.CreateModel(
            name="CredentialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier for UI", max_length=100
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Credential Categories",
                "db_table": "credentials_credential_category",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="credentialtype",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credential_types",
                to="credentials.credentialcategory",
            ),
            preserve_default=False,
        ),
    ]
