// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/agents": {
    params: {};
  };
  "/agents/create": {
    params: {};
  };
  "/agents/:id": {
    params: {
      "id": string;
    };
  };
  "/agents/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/workflows": {
    params: {};
  };
  "/workflows/create/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/workflows/:id": {
    params: {
      "id": string;
    };
  };
  "/workflows/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/tools": {
    params: {};
  };
  "/credentials": {
    params: {};
  };
  "/credentials/create": {
    params: {};
  };
  "/credentials/:id/edit": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/projects" | "/agents" | "/agents/create" | "/agents/:id" | "/agents/:id/edit" | "/workflows" | "/workflows/create/:projectId" | "/workflows/:id" | "/workflows/:id/edit" | "/tools" | "/credentials" | "/credentials/create" | "/credentials/:id/edit";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/agents.tsx": {
    id: "routes/agents";
    page: "/agents";
  };
  "routes/agents/create.tsx": {
    id: "routes/agents/create";
    page: "/agents/create";
  };
  "routes/agents/$id.tsx": {
    id: "routes/agents/$id";
    page: "/agents/:id";
  };
  "routes/agents/$id.edit.tsx": {
    id: "routes/agents/$id.edit";
    page: "/agents/:id/edit";
  };
  "routes/workflows.tsx": {
    id: "routes/workflows";
    page: "/workflows";
  };
  "routes/workflows/create.tsx": {
    id: "routes/workflows/create";
    page: "/workflows/create/:projectId";
  } | {
    id: "workflow-edit";
    page: "/workflows/:id/edit";
  };
  "routes/workflows/$id.tsx": {
    id: "routes/workflows/$id";
    page: "/workflows/:id";
  };
  "routes/tools.tsx": {
    id: "routes/tools";
    page: "/tools";
  };
  "routes/credentials.tsx": {
    id: "routes/credentials";
    page: "/credentials";
  };
  "routes/credentials/create.tsx": {
    id: "routes/credentials/create";
    page: "/credentials/create";
  };
  "routes/credentials/$id.edit.tsx": {
    id: "routes/credentials/$id.edit";
    page: "/credentials/:id/edit";
  };
};